/******************************************************************************
 *
 * File: MainWindow.cs
 *
 * Description: Main window for the MultiCamViewer application, responsible for managing the user interface and camera stream playback using LibVLCSharp. 
 * This app was mostly generated by AI based on a prompt describing the desired functionality, and the code is structured to provide a responsive and user-friendly experience 
 * for viewing multiple camera feeds simultaneously.
 *
 * Date: 08.06.2026		Author: Andrei Kravtsov
 *
 *****************************************************************************/
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Threading;
using LibVLCSharp.Avalonia;
using LibVLCSharp.Shared;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MultiCamViewer
{
    /// <summary>
    /// Defines the layout options for displaying multiple camera feeds in the application. 
    /// </summary>
    public enum CameraLayout
    {
        Grid,
        Horizontal,
        Vertical
    }

    public partial class MainWindow : Window
    {
        #region Member variables

        private const int CameraTotal = 4;
        private const int RtspTimeoutMicroseconds = 5_000_000;
        private const int NetworkCacheMilliseconds = 1_000;
        private const string NormalCameraVideoAspectRatio = "16:9";
        private const string RotatedCameraVideoAspectRatio = "9:16";

        private readonly IReadOnlyList<Border> _cameraPanels;
        private readonly IReadOnlyList<ToggleButton> _countButtons;
        private readonly IReadOnlyList<ToggleButton> _layoutButtons;
        private readonly IReadOnlyList<ToggleButton> _cameraEnabledButtons;
        private readonly IReadOnlyList<StackPanel> _cameraSettingsFields;
        private readonly IReadOnlyList<TextBox> _cameraUrlTextBoxes;
        private readonly IReadOnlyList<TextBox> _cameraLoginTextBoxes;
        private readonly IReadOnlyList<TextBox> _cameraPasswordTextBoxes;
        private readonly IReadOnlyList<ComboBox> _cameraStreamComboBoxes;
        private readonly IReadOnlyList<ComboBox> _cameraTransportComboBoxes;
        private readonly IReadOnlyList<TextBlock> _cameraUrlPreviewTexts;
        private readonly IReadOnlyList<StackPanel> _cameraPlaceholderPanels;
        private readonly IReadOnlyList<StackPanel> _cameraStatusPanels;
        private readonly IReadOnlyList<Border> _cameraStatusOverlays;
        private readonly IReadOnlyList<TextBlock> _cameraStatusTitleTexts;
        private readonly IReadOnlyList<TextBlock> _cameraStatusDetailTexts;
        private readonly IReadOnlyList<Grid> _cameraVideoHosts;
        private readonly DispatcherTimer _controlsHideTimer;
        private readonly DispatcherTimer _autoReconnectTimer;

        private readonly bool[] _cameraEnabled = [true, true, true, true];
        private readonly bool[] _cameraPlaying = [false, false, false, false];
        private readonly bool[] _cameraPlayStarting = [false, false, false, false];
        private readonly string[] _cameraPlaybackKeys = ["", "", "", ""];
        private readonly int[] _cameraPlaybackVersions = new int[CameraTotal];
        private readonly DateTimeOffset[] _lastReconnectAttemptAt = new DateTimeOffset[CameraTotal];
        private readonly DateTimeOffset[] _suppressLostStatusUntil = new DateTimeOffset[CameraTotal];

        private readonly MediaPlayer?[] _mediaPlayers = new MediaPlayer?[CameraTotal];
        private LibVLC? _libVlc;

        private bool _vlcReady;
        private bool _vlcInitializing;
        private bool _suspendPlaybackSync;
        private bool _playbackRequested;
        private int _cameraCount = 4;
        private CameraLayout _cameraLayout = CameraLayout.Grid;

        #endregion /Member variables

        public MainWindow()
        {
            InitializeComponent();

            WindowState = WindowState.FullScreen;

            #region Init controls

            _cameraPanels =
             [
                 Camera1Panel,
                Camera2Panel,
                Camera3Panel,
                Camera4Panel
             ];

            _countButtons =
            [
                CameraCount1Button,
                CameraCount2Button,
                CameraCount3Button,
                CameraCount4Button
            ];

            _layoutButtons =
            [
                GridLayoutButton,
                HorizontalLayoutButton,
                VerticalLayoutButton
            ];

            _cameraEnabledButtons =
            [
                Camera1EnabledButton,
                Camera2EnabledButton,
                Camera3EnabledButton,
                Camera4EnabledButton
            ];

            _cameraSettingsFields =
            [
                Camera1SettingsFields,
                Camera2SettingsFields,
                Camera3SettingsFields,
                Camera4SettingsFields
            ];

            _cameraUrlTextBoxes =
            [
                Camera1UrlTextBox,
                Camera2UrlTextBox,
                Camera3UrlTextBox,
                Camera4UrlTextBox
            ];

            _cameraLoginTextBoxes =
            [
                Camera1LoginTextBox,
                Camera2LoginTextBox,
                Camera3LoginTextBox,
                Camera4LoginTextBox
            ];

            _cameraPasswordTextBoxes =
            [
                Camera1PasswordTextBox,
                Camera2PasswordTextBox,
                Camera3PasswordTextBox,
                Camera4PasswordTextBox
            ];

            _cameraStreamComboBoxes =
            [
                Camera1StreamComboBox,
                Camera2StreamComboBox,
                Camera3StreamComboBox,
                Camera4StreamComboBox
            ];

            _cameraTransportComboBoxes =
            [
                Camera1TransportComboBox,
                Camera2TransportComboBox,
                Camera3TransportComboBox,
                Camera4TransportComboBox
            ];

            _cameraUrlPreviewTexts =
            [
                Camera1UrlPreviewText,
                Camera2UrlPreviewText,
                Camera3UrlPreviewText,
                Camera4UrlPreviewText
            ];

            _cameraPlaceholderPanels =
            [
                Camera1PlaceholderPanel,
                Camera2PlaceholderPanel,
                Camera3PlaceholderPanel,
                Camera4PlaceholderPanel
            ];

            _cameraStatusPanels =
            [
                Camera1StatusPanel,
                Camera2StatusPanel,
                Camera3StatusPanel,
                Camera4StatusPanel
            ];

            _cameraStatusOverlays =
            [
                Camera1StatusOverlay,
                Camera2StatusOverlay,
                Camera3StatusOverlay,
                Camera4StatusOverlay
            ];

            _cameraStatusTitleTexts =
            [
                Camera1StatusTitleText,
                Camera2StatusTitleText,
                Camera3StatusTitleText,
                Camera4StatusTitleText
            ];

            _cameraStatusDetailTexts =
            [
                Camera1StatusDetailText,
                Camera2StatusDetailText,
                Camera3StatusDetailText,
                Camera4StatusDetailText
            ];

            _cameraVideoHosts =
            [
                Camera1VideoHost,
                Camera2VideoHost,
                Camera3VideoHost,
                Camera4VideoHost
            ];

            #endregion /Init controls

            _controlsHideTimer = new DispatcherTimer
            {
                Interval = TimeSpan.FromSeconds(4)
            };
            _controlsHideTimer.Tick += (_, _) => HideControlsOverlay();

            _autoReconnectTimer = new DispatcherTimer
            {
                Interval = TimeSpan.FromSeconds(5)
            };
            _autoReconnectTimer.Tick += (_, _) => AutoReconnectCameraStreams();
            _autoReconnectTimer.Start();

            SizeChanged += MainWindow_SizeChanged;

            LoadSettings();
            ApplyCameraLayout();
        }

        #region Overrides

        /// <summary>
        /// Overrides the OnOpened method to perform asynchronous initialization tasks when the window is opened.
        /// </summary>
        /// <param name="e"></param>
        protected override async void OnOpened(EventArgs e)
        {
            try
            {
                base.OnOpened(e);

                ApplyScreenOrientationUi();
                await Task.Delay(1500);
                await StartLivePlaybackAsync();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error during application startup");
                LayoutStatusText.Text = "Error initializing application";
            }
        }

        /// <summary>
        /// Overrides the OnClosed method to perform cleanup tasks when the window is closed.
        /// </summary>
        /// <param name="e"></param>
        protected override void OnClosed(EventArgs e)
        {
            try
            {
                _suspendPlaybackSync = true;
                _autoReconnectTimer.Stop();

                StopAllCameraStreams();
                DisposeVlcPlayback();

                base.OnClosed(e);
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error during application shutdown");
            }
        }

        #endregion /Overrides

        #region Settings auxiliary methods

        /// <summary>
        /// Constructs the file path for storing the application settings, ensuring it is located in a user-specific application data directory.
        /// </summary>
        /// <returns></returns>
        private string GetSettingsPath()
        {
            try
            {
                var configRoot = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);

                if (string.IsNullOrWhiteSpace(configRoot))
                {
                    configRoot = AppContext.BaseDirectory;
                }
                return Path.Combine(configRoot, "MultiCamViewer", "settings.json");
            }
            catch
            {
                throw;
            }
        }


        /// <summary>
        /// Attempts to load the application settings from a JSON file on disk. 
        /// If the file does not exist or an error occurs during loading, default settings are returned instead. 
        /// </summary>
        /// <returns></returns>
        private AppSettings LoadSettingsFromDisk()
        {
            try
            {
                var path = GetSettingsPath();

                if (!File.Exists(path))
                    return AppSettings.CreateDefault();

                var json = File.ReadAllText(path);
                return JsonSerializer.Deserialize<AppSettings>(json) ?? AppSettings.CreateDefault();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Unable to load settings from disk");
                return AppSettings.CreateDefault();
            }
        }

        /// <summary>
        /// Updates the camera URL preview text blocks to reflect the current values entered in the camera URL text boxes.
        /// </summary>
        private void UpdateCameraUrlPreviews()
        {
            for (var index = 0; index < _cameraUrlPreviewTexts.Count; index++)
            {
                _cameraUrlPreviewTexts[index].Text = _cameraUrlTextBoxes[index].Text ?? string.Empty;
            }
        }

        /// <summary>
        /// Loads the application settings from disk and applies them to the user interface and internal state.
        /// </summary>
        private void LoadSettings()
        {
            var settings = LoadSettingsFromDisk();
            ApplySettings(settings);
        }

        /// <summary>
        /// Applies the provided application settings to the user interface and internal state of the application.
        /// </summary>
        /// <param name="settings"></param>
        private void ApplySettings(AppSettings settings)
        {
            try
            {
                _cameraCount = Math.Clamp(settings.CameraCount, 0, CameraTotal);
                _cameraLayout = Enum.TryParse<CameraLayout>(settings.Layout, out var layout) ? layout : CameraLayout.Grid;

                for (var index = 0; index < CameraTotal; index++)
                {
                    var cameraSettings = index < settings.Cameras.Count
                        ? settings.Cameras[index]
                        : CameraSettings.CreateDefault(index);

                    _cameraEnabled[index] = cameraSettings.Enabled;
                    _cameraEnabledButtons[index].IsChecked = cameraSettings.Enabled;
                    _cameraSettingsFields[index].IsEnabled = cameraSettings.Enabled;
                    _cameraUrlTextBoxes[index].Text = cameraSettings.Url;
                    _cameraLoginTextBoxes[index].Text = cameraSettings.Login;
                    _cameraPasswordTextBoxes[index].Text = cameraSettings.Password;
                    _cameraStreamComboBoxes[index].SelectedIndex = Math.Clamp(cameraSettings.StreamIndex, 0, 2);
                    _cameraTransportComboBoxes[index].SelectedIndex = Math.Clamp(cameraSettings.TransportIndex, 0, 1);
                }
                UpdateCameraUrlPreviews();
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Serializes the current application settings to a JSON file on disk, ensuring that the necessary directory structure exists before writing the file.
        /// </summary>
        private void SaveSettings()
        {
            try
            {
                var settings = CaptureSettings();
                var path = GetSettingsPath();
                var directory = Path.GetDirectoryName(path);

                if (!string.IsNullOrWhiteSpace(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                var json = JsonSerializer.Serialize(settings, new JsonSerializerOptions
                {
                    WriteIndented = true
                });
                File.WriteAllText(path, json);
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Unable to save settings to disk");
                throw;
            }
        }

        /// <summary>
        /// Captures the current application settings from the user interface and internal state, constructing an AppSettings object 
        /// that represents the current configuration of the application.
        /// </summary>
        /// <returns></returns>
        private AppSettings CaptureSettings()
        {
            var settings = new AppSettings
            {
                CameraCount = _cameraCount,
                Layout = _cameraLayout.ToString()
            };

            for (var index = 0; index < CameraTotal; index++)
            {
                settings.Cameras.Add(new CameraSettings
                {
                    Enabled = _cameraEnabled[index],
                    Url = _cameraUrlTextBoxes[index].Text ?? string.Empty,
                    Login = _cameraLoginTextBoxes[index].Text ?? string.Empty,
                    Password = _cameraPasswordTextBoxes[index].Text ?? string.Empty,
                    StreamIndex = _cameraStreamComboBoxes[index].SelectedIndex,
                    TransportIndex = _cameraTransportComboBoxes[index].SelectedIndex
                });
            }
            return settings;
        }

        #endregion /Settings auxiliary methods

        #region Camera methods

        /// <summary>
        /// Ensures that the camera stream for the specified index is playing if it is enabled and visible.
        /// </summary>
        /// <param name="index"></param>
        private void EnsureCameraPlaying(int index)
        {
            try
            {
                var mediaPlayer = _mediaPlayers[index];

                if (_libVlc is null || mediaPlayer is null)
                    return;

                var url = BuildCameraUrl(index);
                var transportIndex = _cameraTransportComboBoxes[index].SelectedIndex;
                var playbackKey = $"{url}|{transportIndex}|{_cameraLayout}";

                if (_cameraPlaying[index] && _cameraPlaybackKeys[index] == playbackKey && mediaPlayer.IsPlaying)
                    return;

                if (_cameraPlayStarting[index])
                    return;

                StopCameraStream(index);

                if (string.IsNullOrWhiteSpace(url))
                {
                    ShowCameraStatus(index, "NO STREAM", "Camera URL is empty");
                    return;
                }

                var playbackVersion = _cameraPlaybackVersions[index];
                _cameraPlayStarting[index] = true;
                _lastReconnectAttemptAt[index] = DateTimeOffset.UtcNow;
                ShowCameraStatus(index, "CONNECTING", "Opening stream...");
                _ = StartCameraPlaybackAsync(index, playbackVersion, mediaPlayer, url, transportIndex, playbackKey);
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Starts the playback of the camera stream for the specified index by creating a new Media object with the appropriate options based on the camera settings,
        /// </summary>
        /// <param name="index"></param>
        /// <param name="playbackVersion"></param>
        /// <param name="mediaPlayer"></param>
        /// <param name="url"></param>
        /// <param name="transportIndex"></param>
        /// <param name="playbackKey"></param>
        /// <returns></returns>
        private async Task StartCameraPlaybackAsync(int index, int playbackVersion, MediaPlayer mediaPlayer, string url, int transportIndex, string playbackKey)
        {
            bool playStarted;

            try
            {
                playStarted = await Task.Run(() =>
                {
                    var libVlc = _libVlc;
                    if (libVlc is null)
                        return false;

                    using var media = new Media(libVlc, url, FromType.FromLocation);

                    if (transportIndex == 0)
                        media.AddOption(":rtsp-tcp");

                    media.AddOption(":no-audio");
                    media.AddOption($":rtsp-timeout={RtspTimeoutMicroseconds}");
                    media.AddOption($":network-caching={NetworkCacheMilliseconds}");
                    media.AddOption($":live-caching={NetworkCacheMilliseconds}");

                    return mediaPlayer.Play(media);
                });
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error starting camera playback");
                playStarted = false;
            }

            Dispatcher.UIThread.Post(() =>
            {
                if (index < 0 || index >= CameraTotal)
                    return;

                _cameraPlayStarting[index] = false;

                if (playbackVersion != _cameraPlaybackVersions[index]
                    || !playStarted
                    || _suspendPlaybackSync
                    || !_cameraPanels[index].IsVisible
                    || !_cameraEnabled[index])
                {
                    _cameraPlaying[index] = false;
                    _cameraPlaybackKeys[index] = string.Empty;

                    if (!playStarted
                        && !_suspendPlaybackSync
                        && _cameraPanels[index].IsVisible
                        && _cameraEnabled[index])
                    {
                        ShowCameraStatus(index, "STREAM LOST", "Reconnecting...");
                    }

                    return;
                }

                _cameraPlaying[index] = true;
                _cameraPlaybackKeys[index] = playbackKey;
                ApplyCameraVideoAspectRatio();
            });
        }

        /// <summary>
        /// Synchronizes the playback of camera streams based on the current visibility and enabled state of each camera panel.
        /// </summary>
        private void SynchronizeCameraPlayback()
        {
            try
            {
                if (_suspendPlaybackSync || !_playbackRequested || !_vlcReady)
                    return;

                for (var index = 0; index < CameraTotal; index++)
                {
                    if (_cameraPanels[index].IsVisible && _cameraEnabled[index])
                        EnsureCameraPlaying(index);

                    else
                        StopCameraStream(index);
                }
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Automatically attempts to reconnect camera streams that have stopped playing due to errors or network issues.
        /// </summary>
        private void AutoReconnectCameraStreams()
        {
            try
            {
                if (_suspendPlaybackSync || !_playbackRequested || !_vlcReady)
                    return;

                for (var index = 0; index < CameraTotal; index++)
                {
                    if (!_cameraPanels[index].IsVisible || !_cameraEnabled[index])
                        continue;

                    var mediaPlayer = _mediaPlayers[index];
                    if (mediaPlayer is null)
                        continue;

                    if (_cameraPlayStarting[index])
                        continue;

                    var url = BuildCameraUrl(index);
                    if (string.IsNullOrWhiteSpace(url))
                        continue;

                    if (_cameraPlaying[index] && mediaPlayer.IsPlaying)
                        continue;

                    if (DateTimeOffset.UtcNow - _lastReconnectAttemptAt[index] < TimeSpan.FromSeconds(10))
                        continue;

                    ShowCameraStatus(index, "STREAM LOST", "Reconnecting...");
                    StopCameraStream(index, hideStatus: false);
                    EnsureCameraPlaying(index);
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error during camera auto reconnect");
            }
        }

        /// <summary>
        /// Registers event handlers for the specified media player to monitor for playback errors and end of stream events.
        /// </summary>
        /// <param name="mediaPlayer"></param>
        /// <param name="index"></param>
        private void RegisterCameraPlaybackEvents(MediaPlayer mediaPlayer, int index)
        {
            mediaPlayer.EncounteredError += (_, _) => MarkCameraForReconnect(index);
            mediaPlayer.EndReached += (_, _) => MarkCameraForReconnect(index);
            mediaPlayer.Playing += (_, _) => MarkCameraAsLive(index);
        }

        /// <summary>
        /// Marks the camera stream for the specified index to be reconnected by setting its playing state to false and clearing its playback key.
        /// </summary>
        /// <param name="index"></param>
        private void MarkCameraForReconnect(int index)
        {
            Dispatcher.UIThread.Post(() =>
            {
                if (index < 0 || index >= CameraTotal)
                    return;

                if (_cameraPlayStarting[index])
                    return;

                if (DateTimeOffset.UtcNow < _suppressLostStatusUntil[index])
                    return;

                ShowCameraStatus(index, "STREAM LOST", "Reconnecting...");
                StopCameraStream(index, hideStatus: false);
            });
        }

        /// <summary>
        /// Marks the camera stream for the specified index as live by hiding any status overlays and allowing the video host to be visible again.
        /// </summary>
        /// <param name="index"></param>
        private void MarkCameraAsLive(int index)
        {
            Dispatcher.UIThread.Post(() =>
            {
                if (index < 0 || index >= CameraTotal)
                    return;

                HideCameraStatus(index);
            });
        }

        /// <summary>
        /// Stops all camera streams
        /// </summary>
        private void StopAllCameraStreams()
        {
            try
            {
                for (var index = 0; index < CameraTotal; index++)
                    StopCameraStream(index);
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Stops the camera stream for the specified index if it is currently playing, and resets the playback state for that camera.
        /// </summary>
        /// <param name="index"></param>
        private void StopCameraStream(int index, bool hideStatus = true)
        {
            try
            {
                var mediaPlayer = _mediaPlayers[index];

                _cameraPlaybackVersions[index]++;
                _cameraPlayStarting[index] = false;

                if (hideStatus)
                    _suppressLostStatusUntil[index] = DateTimeOffset.UtcNow.AddSeconds(1);

                if (mediaPlayer?.IsPlaying == true)
                    mediaPlayer.Stop();
                _cameraPlaying[index] = false;
                _cameraPlaybackKeys[index] = string.Empty;

                if (hideStatus)
                    HideCameraStatus(index);
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Builds the camera URL for the specified index by combining the base URL entered in the camera URL text box with the login credentials if provided.
        /// </summary>
        /// <param name="index"></param>
        /// <returns></returns>
        private string BuildCameraUrl(int index)
        {
            try
            {
                var url = ApplyStreamSelectionToUrl(
                    _cameraUrlTextBoxes[index].Text ?? string.Empty,
                    _cameraStreamComboBoxes[index].SelectedIndex);
                var login = _cameraLoginTextBoxes[index].Text ?? string.Empty;
                var password = _cameraPasswordTextBoxes[index].Text ?? string.Empty;

                if (string.IsNullOrWhiteSpace(url) || string.IsNullOrWhiteSpace(login))
                    return url;

                if (!Uri.TryCreate(url, UriKind.Absolute, out var uri) || !string.IsNullOrEmpty(uri.UserInfo))
                    return url;

                var builder = new UriBuilder(uri)
                {
                    UserName = login,
                    Password = password
                };
                return builder.Uri.ToString();
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Applies the stream selection to the provided camera URL by replacing known placeholders or patterns with the appropriate values based on the selected stream index.
        /// </summary>
        /// <param name="url">The camera URL to which the stream selection will be applied.</param>
        /// <param name="streamIndex">The index of the stream to apply (0 for main, 1 for sub, 2 for auto).</param>
        /// <returns>The modified camera URL with the appropriate stream selection applied.</returns>
        private static string ApplyStreamSelectionToUrl(string url, int streamIndex)
        {
            if (string.IsNullOrWhiteSpace(url))
                return url;

            var streamName = streamIndex switch
            {
                1 => "sub",
                2 => "auto",
                _ => "main"
            };

            var streamNumber = streamIndex switch
            {
                1 => "1",
                _ => "0"
            };

            var channelNumber = streamIndex switch
            {
                1 => "102",
                _ => "101"
            };

            var result = url
                .Replace("{stream}", streamName, StringComparison.OrdinalIgnoreCase)
                .Replace("{streamIndex}", streamNumber, StringComparison.OrdinalIgnoreCase)
                .Replace("{channel}", channelNumber, StringComparison.OrdinalIgnoreCase)
                .Replace("{subtype}", streamNumber, StringComparison.OrdinalIgnoreCase);

            if (!string.Equals(result, url, StringComparison.Ordinal))
                return result;

            return streamIndex switch
            {
                0 => ApplyKnownMainStreamPatterns(url),
                1 => ApplyKnownSubStreamPatterns(url),
                _ => url
            };
        }

        /// <summary>
        /// Applies known patterns for selecting the main stream in camera URLs by replacing common placeholders or patterns that indicate the main stream with the appropriate values.
        /// </summary>
        /// <param name="url">The camera URL to which the patterns will be applied.</param>
        /// <returns>The modified camera URL with the main stream patterns applied.</returns>
        private static string ApplyKnownMainStreamPatterns(string url)
        {
            var result = Regex.Replace(url, @"(?<=/Streaming/Channels/)102\b", "101", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"([?&]subtype=)1\b", "${1}0", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"([?&]stream=)sub\b", "${1}main", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"(?<=/)sub(?=/?(?:$|[?#]))", "main", RegexOptions.IgnoreCase);
            return result;
        }

        /// <summary>
        /// Applies known patterns for selecting the sub stream in camera URLs by replacing common placeholders or patterns that indicate the sub stream with the appropriate values.       
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        private static string ApplyKnownSubStreamPatterns(string url)
        {
            var result = Regex.Replace(url, @"(?<=/Streaming/Channels/)101\b", "102", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"([?&]subtype=)0\b", "${1}1", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"([?&]stream=)main\b", "${1}sub", RegexOptions.IgnoreCase);
            result = Regex.Replace(result, @"(?<=/)main(?=/?(?:$|[?#]))", "sub", RegexOptions.IgnoreCase);
            return result;
        }

        /// <summary>
        /// Initiates the live playback of camera streams. If VLC is already initialized and ready, it synchronizes the camera playback immediately.
        /// </summary>
        /// <returns></returns>
        private async Task StartLivePlaybackAsync()
        {
            try
            {
                _playbackRequested = true;

                if (_vlcReady)
                {
                    SynchronizeCameraPlayback();
                    return;
                }
                await InitializeVlcPlaybackAsync();
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Initializes the VLC media player library and sets up the media players for each camera feed.
        /// </summary>
        /// <returns></returns>
        private async Task InitializeVlcPlaybackAsync()
        {
            if (_vlcReady || _vlcInitializing)
                return;

            _vlcInitializing = true;
            await Task.Delay(1000);

            LibVLC libVlc;

            try
            {
                var rotateVideo = ShouldRotateVideo();
                libVlc = await Task.Run(() =>
                {
                    Core.Initialize();
                    return new LibVLC(CreateLibVlcOptions(rotateVideo));
                });
            }
            catch
            {
                _vlcInitializing = false;
                LayoutStatusText.Text = "VLC initialization failed";
                return;
            }

            _libVlc = libVlc;
            for (var index = 0; index < CameraTotal; index++)
            {
                var mediaPlayer = new MediaPlayer(_libVlc)
                {
                    EnableMouseInput = false,
                    EnableKeyInput = false,
                    Mute = true,
                    Scale = 0,
                    AspectRatio = GetCameraVideoAspectRatio(),
                    CropGeometry = GetCameraVideoAspectRatio()
                };
                RegisterCameraPlaybackEvents(mediaPlayer, index);

                _mediaPlayers[index] = mediaPlayer;
                var videoView = new VideoView
                {
                    MediaPlayer = mediaPlayer,
                    Focusable = false,
                    HorizontalAlignment = HorizontalAlignment.Stretch,
                    VerticalAlignment = VerticalAlignment.Stretch
                };
                _cameraVideoHosts[index].Children.Clear();
                _cameraVideoHosts[index].Children.Add(videoView);
            }

            _vlcReady = true;
            _vlcInitializing = false;
            SynchronizeCameraPlayback();
        }

        /// <summary>
        /// Reinitializes the VLC playback by stopping all camera streams, detaching video views, 
        /// disposing of the existing VLC instance, and then initializing a new VLC instance.
        /// </summary>
        /// <returns></returns>
        private async Task ReinitializeVlcPlaybackAsync()
        {
            if (_vlcInitializing)
                return;

            _suspendPlaybackSync = true;
            StopAllCameraStreams();
            DetachVideoViews();
            await Task.Delay(300);
            DisposeVlcPlayback();
            _suspendPlaybackSync = false;
            await InitializeVlcPlaybackAsync();
        }

        /// <summary>
        /// Detaches the video views from the camera video hosts by setting their MediaPlayer property to null and clearing the children of each video host panel.
        /// </summary>
        private void DetachVideoViews()
        {
            foreach (var host in _cameraVideoHosts)
            {
                foreach (var child in host.Children)
                {
                    if (child is VideoView videoView)
                        videoView.MediaPlayer = null;
                }

                host.Children.Clear();
            }
        }

        /// <summary>
        /// Disposes of the VLC media players and the VLC instance, resets the playback state for each camera, and marks VLC as not ready.
        /// </summary>
        private void DisposeVlcPlayback()
        {
            DetachVideoViews();

            for (var index = 0; index < CameraTotal; index++)
            {
                _mediaPlayers[index]?.Dispose();
                _mediaPlayers[index] = null;
                _cameraPlaying[index] = false;
                _cameraPlaybackKeys[index] = string.Empty;
            }

            _libVlc?.Dispose();
            _libVlc = null;
            _vlcReady = false;
        }

        /// <summary>
        /// Creates an array of options to be passed to the LibVLC constructor based on whether the video should be rotated for vertical layout.
        /// </summary>
        /// <param name="rotateVideo"></param>
        /// <returns></returns>
        private static string[] CreateLibVlcOptions(bool rotateVideo)
        {
            var options = new List<string>
            {
                "--no-osd",
                "--no-video-title-show",
                "--quiet"
            };

            if (rotateVideo)
            {
                options.Add("--video-filter=transform");
                options.Add("--transform-type=270");
            }

            return [.. options];
        }

        /// <summary>
        /// Determines whether the video should be rotated based on the current camera layout. 
        /// If the layout is vertical, the video should be rotated to fit the orientation of the screen.
        /// </summary>
        /// <returns></returns>
        private bool ShouldRotateVideo()
        {
            return _cameraLayout == CameraLayout.Vertical;
        }

        /// <summary>
        ///Restarts the camera streams for all currently visible camera panels. 
        /// </summary>
        private void RestartVisibleCameraStreams()
        {
            try
            {
                for (var index = 0; index < CameraTotal; index++)
                {
                    if (_cameraPanels[index].IsVisible)
                        StopCameraStream(index);
                }
            }
            catch
            {
                throw;
            }
        }

        #endregion /Camera methods

        #region UI auxiliary methods

        /// <summary>
        /// Displays the controls overlay and hides the camera video hosts to ensure that the controls are prominently visible.
        /// </summary>
        private void ShowControlsOverlay()
        {
            try
            {
                SetVideoHostsVisible(false);
                ControlsOverlay.IsVisible = true;
                _controlsHideTimer.Stop();
                _controlsHideTimer.Start();
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Hides the controls overlay and makes the camera video hosts visible again if the settings panel is not currently visible.
        /// </summary>
        private void HideControlsOverlay()
        {
            try
            {
                _controlsHideTimer.Stop();
                ControlsOverlay.IsVisible = false;

                if (!SettingsPanel.IsVisible)
                    SetVideoHostsVisible(true);
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Sets the visibility of the camera video host controls based on the provided boolean value. 
        /// </summary>
        /// <param name="isVisible"></param>
        private void SetVideoHostsVisible(bool isVisible)
        {
            for (var index = 0; index < _cameraVideoHosts.Count; index++)
                _cameraVideoHosts[index].IsVisible = isVisible && !_cameraStatusOverlays[index].IsVisible;
        }

        /// <summary>
        /// Displays a status overlay on top of the camera video host for the specified index, showing the provided title and detail messages to indicate the current status of the camera stream (e.g., connecting, stream lost, no stream).
        /// </summary>
        /// <param name="index">The index of the camera for which to display status.</param>
        /// <param name="title">The title to display in the status overlay.</param>
        /// <param name="detail">The detail message to display in the status overlay.</param>
        private void ShowCameraStatus(int index, string title, string detail)
        {
            if (index < 0 || index >= CameraTotal)
                return;

            _cameraStatusTitleTexts[index].Text = title;
            _cameraStatusDetailTexts[index].Text = detail;
            _cameraStatusOverlays[index].IsVisible = true;
            _cameraVideoHosts[index].IsVisible = false;
        }

        /// <summary>
        /// Hides the status overlay for the camera at the specified index and makes the camera video host visible again if it should be shown based on the current visibility of the camera panel and other overlays.  
        /// </summary>
        /// <param name="index"></param>
        private void HideCameraStatus(int index)
        {
            if (index < 0 || index >= CameraTotal)
                return;

            _cameraStatusOverlays[index].IsVisible = false;
            _cameraVideoHosts[index].IsVisible = ShouldShowCameraVideoHost(index);
        }

        /// <summary>
        /// Determines whether the camera video host for the specified index should be visible based on the visibility of the camera panel and other overlays.
        /// </summary>
        /// <param name="index"></param>
        /// <returns></returns>
        private bool ShouldShowCameraVideoHost(int index)
        {
            return _cameraPanels[index].IsVisible
                && !ControlsOverlay.IsVisible
                && !SettingsPanel.IsVisible;
        }

        /// <summary>
        /// Reads the enabled state of each camera from the corresponding toggle buttons in the user interface, updates the internal state accordingly,
        /// </summary>
        private void ReadCameraEnabledFromUi()
        {
            for (var index = 0; index < _cameraEnabledButtons.Count; index++)
            {
                _cameraEnabled[index] = _cameraEnabledButtons[index].IsChecked == true;
                _cameraSettingsFields[index].IsEnabled = _cameraEnabled[index];
            }
        }

        /// <summary>
        /// Applies the current camera layout and count settings to the user interface, updating the visibility and arrangement of camera panels,
        /// </summary>
        private void ApplyCameraLayout()
        {
            try
            {
                CameraGrid.RowDefinitions.Clear();
                CameraGrid.ColumnDefinitions.Clear();

                var activePanels = new List<Border>();

                for (var index = 0; index < _cameraPanels.Count; index++)
                {
                    if (_cameraEnabled[index])
                        activePanels.Add(_cameraPanels[index]);
                }

                var activeCameraCount = activePanels.Count;

                if (_cameraCount > activeCameraCount)
                    _cameraCount = activeCameraCount;
                else if (_cameraCount == 0 && activeCameraCount > 0)
                    _cameraCount = 1;

                var rows = 1;
                var columns = 1;

                if (_cameraCount > 0)
                {
                    switch (_cameraLayout)
                    {
                        case CameraLayout.Horizontal:
                            columns = _cameraCount;
                            break;
                        case CameraLayout.Vertical:
                            rows = _cameraCount;
                            break;
                        default:
                            if (_cameraCount == 1)
                            {
                                rows = 1;
                                columns = 1;
                            }
                            else if (_cameraCount == 2)
                            {
                                rows = 1;
                                columns = 2;
                            }
                            else
                            {
                                rows = 2;
                                columns = 2;
                            }
                            break;
                    }
                }

                for (var row = 0; row < rows; row++)
                    CameraGrid.RowDefinitions.Add(new RowDefinition(GridLength.Star));

                for (var column = 0; column < columns; column++)
                    CameraGrid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

                for (var index = 0; index < _cameraPanels.Count; index++)
                {
                    var panel = _cameraPanels[index];
                    panel.IsVisible = false;
                    Grid.SetRow(panel, 0);
                    Grid.SetColumn(panel, 0);
                }

                for (var index = 0; index < activePanels.Count; index++)
                {
                    var panel = activePanels[index];
                    panel.IsVisible = index < _cameraCount;

                    if (panel.IsVisible)
                    {
                        Grid.SetRow(panel, index / columns);
                        Grid.SetColumn(panel, index % columns);
                    }
                }

                UpdateCameraCountButtons(activeCameraCount);
                UpdateCheckedButton(_countButtons, _cameraCount - 1);
                UpdateCheckedButton(_layoutButtons, (int)_cameraLayout);
                UpdateStatusText(rows, columns);
                ApplyScreenOrientationUi();
                ApplyCameraVideoAspectRatio();
                SynchronizeCameraPlayback();
            }
            catch
            {
                throw;
            }
        }

        /// <summary>
        /// Applies adjustments to the user interface layout based on the current screen orientation and camera layout.
        /// </summary>
        private void ApplyScreenOrientationUi()
        {
            if (_cameraLayout == CameraLayout.Vertical)
            {
                ApplyVerticalScreenOrientationUi();
                return;
            }

            ApplyNormalScreenOrientationUi();
        }

        /// <summary>
        ///Applies the appropriate aspect ratio settings to the camera video hosts based on whether the video is rotated for vertical layout or not, ensuring that the video is displayed with the correct proportions in each layout configuration.
        /// </summary>
        private void ApplyCameraVideoAspectRatio()
        {
            var aspectRatio = GetCameraVideoAspectRatio();

            for (var index = 0; index < CameraTotal; index++)
            {
                var mediaPlayer = _mediaPlayers[index];
                if (mediaPlayer is null)
                    continue;

                mediaPlayer.Scale = 0;
                mediaPlayer.AspectRatio = aspectRatio;
                mediaPlayer.CropGeometry = aspectRatio;
            }
        }

        /// <summary>
        /// Determines the appropriate aspect ratio string to use for the camera video based on whether the video should be rotated for vertical layout or not.
        /// </summary>
        /// <returns></returns>
        private string GetCameraVideoAspectRatio()
        {
            return ShouldRotateVideo()
                ? RotatedCameraVideoAspectRatio
                : NormalCameraVideoAspectRatio;
        }

        /// <summary>
        ///Applies the user interface layout for normal screen orientation, arranging the controls and camera panels in a way that is optimized for horizontal layouts.
        /// </summary>
        private void ApplyNormalScreenOrientationUi()
        {
            RootView.RowDefinitions.Clear();
            RootView.RowDefinitions.Add(new RowDefinition(new GridLength(4)));
            RootView.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            RootView.ColumnDefinitions.Clear();
            RootView.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

            Grid.SetRow(TopActivationStrip, 0);
            Grid.SetColumn(TopActivationStrip, 0);
            Grid.SetRowSpan(TopActivationStrip, 1);
            Grid.SetColumnSpan(TopActivationStrip, 1);

            Grid.SetRow(CameraGrid, 1);
            Grid.SetColumn(CameraGrid, 0);
            Grid.SetRowSpan(CameraGrid, 1);
            Grid.SetColumnSpan(CameraGrid, 1);

            Grid.SetRow(ControlsOverlay, 0);
            Grid.SetColumn(ControlsOverlay, 0);
            Grid.SetRowSpan(ControlsOverlay, 2);
            Grid.SetColumnSpan(ControlsOverlay, 1);
            ControlsOverlay.Width = double.NaN;
            ControlsOverlay.Height = double.NaN;
            ControlsOverlay.Margin = new Thickness(16);
            ControlsOverlay.HorizontalAlignment = HorizontalAlignment.Stretch;
            ControlsOverlay.VerticalAlignment = VerticalAlignment.Top;
            ResetControlTransform(ControlsOverlay);

            Grid.SetRow(SettingsPanel, 0);
            Grid.SetColumn(SettingsPanel, 0);
            Grid.SetRowSpan(SettingsPanel, 2);
            Grid.SetColumnSpan(SettingsPanel, 1);
            SettingsPanel.Width = 390;
            SettingsPanel.Height = double.NaN;
            SettingsPanel.BorderThickness = new Thickness(1, 0, 0, 0);
            SettingsPanel.HorizontalAlignment = HorizontalAlignment.Right;
            SettingsPanel.VerticalAlignment = VerticalAlignment.Stretch;
            ResetControlTransform(SettingsPanel);

            foreach (var placeholderPanel in _cameraPlaceholderPanels)
            {
                ResetControlTransform(placeholderPanel);
            }

            foreach (var statusPanel in _cameraStatusPanels)
            {
                ResetControlTransform(statusPanel);
            }
        }

        /// <summary>
        /// Applies the user interface layout for vertical screen orientation, rearranging and rotating the controls and camera panels to optimize for a portrait layout.
        /// </summary>
        private void ApplyVerticalScreenOrientationUi()
        {
            RootView.RowDefinitions.Clear();
            RootView.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            RootView.ColumnDefinitions.Clear();
            RootView.ColumnDefinitions.Add(new ColumnDefinition(new GridLength(4)));
            RootView.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

            Grid.SetRow(TopActivationStrip, 0);
            Grid.SetColumn(TopActivationStrip, 0);
            Grid.SetRowSpan(TopActivationStrip, 1);
            Grid.SetColumnSpan(TopActivationStrip, 1);

            var rotatedUiLength = GetRotatedUiLength();

            Grid.SetRow(CameraGrid, 0);
            Grid.SetColumn(CameraGrid, 1);
            Grid.SetRowSpan(CameraGrid, 1);
            Grid.SetColumnSpan(CameraGrid, 1);

            Grid.SetRow(ControlsOverlay, 0);
            Grid.SetColumn(ControlsOverlay, 0);
            Grid.SetRowSpan(ControlsOverlay, 1);
            Grid.SetColumnSpan(ControlsOverlay, 2);
            ControlsOverlay.Width = rotatedUiLength;
            ControlsOverlay.Height = 74;
            ControlsOverlay.Margin = new Thickness(0);
            ControlsOverlay.HorizontalAlignment = HorizontalAlignment.Left;
            ControlsOverlay.VerticalAlignment = VerticalAlignment.Top;
            RotateControlLeft(ControlsOverlay, ControlsOverlay.Width);

            Grid.SetRow(SettingsPanel, 0);
            Grid.SetColumn(SettingsPanel, 0);
            Grid.SetRowSpan(SettingsPanel, 1);
            Grid.SetColumnSpan(SettingsPanel, 2);
            SettingsPanel.Width = rotatedUiLength;
            SettingsPanel.Height = 390;
            SettingsPanel.BorderThickness = new Thickness(0, 0, 0, 1);
            SettingsPanel.HorizontalAlignment = HorizontalAlignment.Left;
            SettingsPanel.VerticalAlignment = VerticalAlignment.Top;
            RotateControlLeft(SettingsPanel, SettingsPanel.Width);

            foreach (var placeholderPanel in _cameraPlaceholderPanels)
            {
                RotateControlLeftAtCenter(placeholderPanel);
            }

            foreach (var statusPanel in _cameraStatusPanels)
            {
                RotateControlLeftAtCenter(statusPanel);
            }
        }

        /// <summary>
        ///Calculates the length to be used for the width of the controls and settings panel when the video is rotated for vertical layout.
        /// </summary>
        /// <returns></returns>
        private double GetRotatedUiLength()
        {
            var height = ClientSize.Height > 0 ? ClientSize.Height : Bounds.Height;
            return height > 0 ? height : 760;
        }

        /// <summary>
        /// Resets the RenderTransform and RenderTransformOrigin properties of the specified control to their default values, effectively removing any rotation or transformation applied to the control.
        /// </summary>
        /// <param name="control"></param>
        private static void ResetControlTransform(Control control)
        {
            control.RenderTransform = null;
            control.RenderTransformOrigin = RelativePoint.TopLeft;
        }

        /// <summary>
        ///Applies a rotation and translation transform to the specified control to rotate it 90 degrees to the left (counterclockwise) around its top-left corner,
        /// </summary>
        /// <param name="control"></param>
        /// <param name="unrotatedWidth"></param>
        private static void RotateControlLeft(Control control, double unrotatedWidth)
        {
            var transform = new TransformGroup();
            transform.Children.Add(new RotateTransform(-90));
            transform.Children.Add(new TranslateTransform(0, unrotatedWidth));

            control.RenderTransformOrigin = RelativePoint.TopLeft;
            control.RenderTransform = transform;
        }

        /// <summary>
        /// Applies a rotation transform to the specified control to rotate it 90 degrees to the left (counterclockwise) around its center point,
        /// </summary>
        /// <param name="control"></param>
        private static void RotateControlLeftAtCenter(Control control)
        {
            control.RenderTransformOrigin = RelativePoint.Center;
            control.RenderTransform = new RotateTransform(-90);
        }

        /// <summary>
        /// Updates the visibility and enabled state of the camera count selection buttons based on the number of active cameras.
        /// </summary>
        /// <param name="activeCameraCount"></param>
        private void UpdateCameraCountButtons(int activeCameraCount)
        {
            for (var index = 0; index < _countButtons.Count; index++)
            {
                var isAvailable = index < activeCameraCount;
                _countButtons[index].IsVisible = isAvailable;
                _countButtons[index].IsEnabled = isAvailable;
            }
        }

        /// <summary>
        /// Updates the checked state of a list of toggle buttons to reflect the currently selected index, 
        /// ensuring that only the button corresponding to the selected index is checked.
        /// </summary>
        /// <param name="buttons"></param>
        /// <param name="checkedIndex"></param>
        private void UpdateCheckedButton(IReadOnlyList<ToggleButton> buttons, int checkedIndex)
        {
            for (var index = 0; index < buttons.Count; index++)
                buttons[index].IsChecked = index == checkedIndex;
        }

        /// <summary>
        /// Updates the status text block to display the current number of active cameras, 
        /// the selected layout, and the arrangement of rows and columns in the camera grid.
        /// </summary>
        /// <param name="rows"></param>
        /// <param name="columns"></param>
        private void UpdateStatusText(int rows, int columns)
        {
            if (_cameraCount == 0)
            {
                LayoutStatusText.Text = "0 cameras - No active cameras";
                return;
            }

            var cameraWord = _cameraCount == 1 ? "camera" : "cameras";
            var layoutName = _cameraLayout switch
            {
                CameraLayout.Horizontal => "Horizontal",
                CameraLayout.Vertical => "Vertical",
                _ => "Grid"
            };

            LayoutStatusText.Text = $"{_cameraCount} {cameraWord} - {layoutName} {columns}x{rows}";
        }

        #endregion /UI auxiliary methods

        #region Event handlers

        /// <summary>
        /// Handles the PointerPressed event on the root view of the application. 
        /// When the user clicks or taps anywhere on the main window, this event is triggered
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void RootView_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            try
            {
                ShowControlsOverlay();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling pointer press event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error","Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the PointerPressed event on the settings panel to prevent the event from propagating to the root view,
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void SettingsPanel_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            e.Handled = true;
        }

        /// <summary>
        /// Handles the SizeChanged event for the main window. When the window is resized, this event is triggered, and the application applies adjustments to the user interface layout and camera video aspect ratio based on the new size and current layout configuration.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void MainWindow_SizeChanged(object? sender, SizeChangedEventArgs e)
        {
            if (_cameraLayout == CameraLayout.Vertical)
                ApplyScreenOrientationUi();

            ApplyCameraVideoAspectRatio();
        }

        /// <summary>
        /// Handles the Click event for the camera count selection buttons. When a user clicks one of the camera count buttons, this event is triggered,
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void CameraCountButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                ShowControlsOverlay();

                _cameraCount = sender switch
                {
                    ToggleButton button when button == CameraCount1Button => 1,
                    ToggleButton button when button == CameraCount2Button => 2,
                    ToggleButton button when button == CameraCount3Button => 3,
                    ToggleButton button when button == CameraCount4Button => 4,
                    _ => _cameraCount
                };

                ApplyCameraLayout();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling camera count click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the camera layout selection buttons. 
        /// When a user clicks one of the layout buttons, this event is triggered, and the application updates the camera layout accordingly.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void LayoutButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                ShowControlsOverlay();

                var wasRotated = ShouldRotateVideo();
                _cameraLayout = sender switch
                {
                    ToggleButton button when button == GridLayoutButton => CameraLayout.Grid,
                    ToggleButton button when button == HorizontalLayoutButton => CameraLayout.Horizontal,
                    ToggleButton button when button == VerticalLayoutButton => CameraLayout.Vertical,
                    _ => _cameraLayout
                };

                var needsVlcReinitialization = _vlcReady && wasRotated != ShouldRotateVideo();
                if (needsVlcReinitialization)
                    _suspendPlaybackSync = true;

                ApplyCameraLayout();

                if (needsVlcReinitialization)
                    await ReinitializeVlcPlaybackAsync();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling layout click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the camera enabled toggle buttons. When a user toggles the enabled state of a camera, this event is triggered,
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void CameraEnabledButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                ShowControlsOverlay();
                ReadCameraEnabledFromUi();
                ApplyCameraLayout();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling camera enabled click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the "Start Live" button. 
        /// When the user clicks this button, the application initiates the live playback of camera streams by calling the StartLivePlaybackAsync method.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void StartLiveButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                ShowControlsOverlay();
                _ = StartLivePlaybackAsync();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling start live click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the "Settings" button. When the user clicks this button, the application displays the settings panel by making it visible,
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void SettingsButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                SettingsPanel.IsVisible = true;
                SetVideoHostsVisible(false);
                ShowControlsOverlay();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling settings click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the "Close Settings" button. When the user clicks this button, 
        /// the application hides the settings panel and updates the visibility of the camera video hosts accordingly.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void CloseSettingsButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                SettingsPanel.IsVisible = false;
                SetVideoHostsVisible(!ControlsOverlay.IsVisible);
                ShowControlsOverlay();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling close settings click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        ///Handles the Click event for the "Save Settings" button. 
        ///When the user clicks this button, the application reads the current camera enabled states from the user interface,
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void SaveSettingsButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                ReadCameraEnabledFromUi();
                UpdateCameraUrlPreviews();
                SaveSettings();
                RestartVisibleCameraStreams();
                ApplyCameraLayout();
                _ = StartLivePlaybackAsync();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling save settings click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        /// <summary>
        /// Handles the Click event for the "Exit Application" button.
        /// When the user clicks this button, the application saves the current settings to disk and then closes the main window,
        /// effectively exiting the application.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private async void ExitApplicationButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                SaveSettings();
                Close();
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error handling exit application click event");
                var box = MessageBoxManager.GetMessageBoxStandard("Error", "Something went wrong", ButtonEnum.Ok);
                await box.ShowAsync();
            }
        }

        #endregion /Event handlers

    }
}
